name: Monitoreo Simple

on:
  schedule:
    - cron: '0 */2 * * *'  # Cada 2 horas
  workflow_dispatch:

jobs:
  check-app:
    runs-on: ubuntu-latest

    steps:
    - name: Chequear estado
      run: |
        curl -f https://localhost:3000/health && echo "✅ App OK" || echo "❌ App caída"