name: CI python app

on:
  push: 
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: COnfigurar python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Ejecutar tests
      run: |
        pytest tests/ -v

    - name: Ejecutar con cobertura
      run: |
        pytest --cov=desafio2 --cov-report=term --cov-report=html

    - name: Guardar reporte
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report 
        path: htmlcov/